apiVersion: 1

datasources:
  - name: PostgreSQL-WMS
    type: postgres
    access: proxy
    url: alta-wms-db-prod:5432
    user: wms_user
    secureJsonData:
      password: 'Dekodera19892603@@@'
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
      timescaledb: false
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      database: 'wms'
    editable: true
    isDefault: true
